base:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  color: 1 1 1 1
link_1: 
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  color: 1 1 1 1
links_2:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  color: 1 1 1 1
link_3:
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  color: 1 1 1 1
link_4: 
  orientation: 0.0 0.0 0.0
  position: 0.0 0.0 0.0
  color: 1 1 1 1
